language: bash
dist: focal
before_install:
  - curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
script:
  - docker version
  - docker buildx version
  - docker buildx create --use --bootstrap
  - docker buildx ls